version: 0.0
os: linux
files:
  - source: /target/test01.war
    destination: /opt/tomcat/webapps/
hooks:
  AfterInstall:
    - location: scripts/RunAfterInstall.sh
      timeout: 181
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
  ApplicationStart:
    - location: scripts/start_tomcat.sh
  ValidateService:
    - location: scripts/MonitorService.sh
      timeout: 3600
