version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn package 
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - target/test01.war
    - appspec.yml
    - scripts/*
  discard-paths: no
