apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
      - image: ${IMAGE}
        imagePullPolicy: Always
        name: ${NAME}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
